export enum Ruolo {
	ADMIN = 'ADMIN',
	DOCENTE = 'DOCENTE',
	AZIENDA = 'AZIENDA',
	DIPENDENTE = 'DIPENDENTE'
}

export enum ModuloServizio {
	PRIVACY = 'PRIVACY',
	SICUREZZA = 'SICUREZZA',
	HACCP = 'HACCP'
}

export enum TipoDocumento {
	DVR = 'DVR',
	HACCP = 'HACCP',
	NOMINA_RESPONSABILE = 'NOMINA_RESPONSABILE',
	REGISTRO_TRATTAMENTI = 'REGISTRO_TRATTAMENTI',
	ALTRO = 'ALTRO',
	ATTESTATO_CORSO = 'ATTESTATO_CORSO'
}

export enum StatoDocumento {
	CARICATO = 'CARICATO',
	IN_ATTESA_FIRMA = 'IN_ATTESA_FIRMA',
	APPROVATO = 'APPROVATO',
	ARCHIVIATO = 'ARCHIVIATO'
}

export enum StatoRinnovo {
	IN_ATTESA = 'IN_ATTESA',
	IN_LAVORAZIONE = 'IN_LAVORAZIONE',
	COMPLETATO = 'COMPLETATO'
}

export enum StatoCorso {
	PROGRAMMATO = 'PROGRAMMATO',
	IN_SVOLGIMENTO = 'IN_SVOLGIMENTO',
	CONCLUSO = 'CONCLUSO',
	ATTESA_FIRMA_DOCENTE = 'ATTESA_FIRMA_DOCENTE',
	VALIDATO = 'VALIDATO'
}

export enum Priorita {
	BASSA = 'BASSA',
	MEDIA = 'MEDIA',
	ALTA = 'ALTA'
}

export enum TipoDPI {
	ELMETTO = 'ELMETTO',
	GUANTI = 'GUANTI',
	SCARPE_ANTINFORTUNISTICHE = 'SCARPE_ANTINFORTUNISTICHE',
	OCCHIALI = 'OCCHIALI',
	ALTRO = 'ALTRO'
}
